#!/bin/bash

# ==============================================================================
# PROJECT: me.aemdevweb.com (Authority Domain)
# DESCRIPTION: Project Structure Reporter (Technical Documentation Generator)
# VERSION: 2.2.0 (2026-01-23)
# IDENTITY: Alongkorl Yomkerd (นายเอ็มซ่ามากส์)
# ==============================================================================

# CONFIGURATION
OUTPUT_FILE="me.aemdevweb-structure.md"
PROJECT_DOMAIN="me.aemdevweb.com"
PROJECT_URL="https://me.aemdevweb.com"

# Next.js 16 Enterprise Directory Whitelist
WHITELIST_DIRS=(
  "app"
  "actions"
  "components"
  "lib"
  "hooks"
  "types"
  "public"
  "data"
  "constants"
  "providers"
  "content"
  "styles"
  "services"
  "config"
)

# Required root-level configuration files (Validated for Next.js 16)
ROOT_FILES=(
  "eslint.config.mjs"
  "mdx-components.tsx"
  "next.config.ts"
  "next.config.mjs"
  "package.json"
  "components.json"
  "tsconfig.json"
  "postcss.config.mjs"
)

# Regex to ignore non-essential or sensitive files
IGNORE_PATTERN="node_modules|\.git|\.next|\.DS_Store|__pycache__|\.env"

# EXECUTION
rm -f "$OUTPUT_FILE"
echo "[INFO] Scanning $PROJECT_DOMAIN project architecture..."

{
  # YAML FRONT MATTER (Optimized for AI/AEM Ingestion)
  echo "---"
  echo "domain: $PROJECT_DOMAIN"
  echo "canonical: $PROJECT_URL"
  echo "generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "type: Architecture Documentation"
  echo "identity: Alongkorl (Authority Entity)"
  echo "---"
  echo ""
  echo "# Project Structure Report"
  echo ""
  echo "> Project: $PROJECT_DOMAIN"
  echo "> URL: $PROJECT_URL"
  echo "> Generated on: $(date '+%Y-%m-%d %H:%M:%S')"
  echo ""

  # --- 1. ROOT CONFIGURATION ---
  echo "## 1. Root Configuration Files"
  echo "The following system files are detected at the project root."
  echo ""

  for file in "${ROOT_FILES[@]}"; do
    if [ -f "$file" ]; then
      echo "- [x] $file"
    else
      # Only show missing if it's not an alternative config format
      [[ "$file" == "next.config.ts" && -f "next.config.mjs" ]] && continue
      [[ "$file" == "next.config.mjs" && -f "next.config.ts" ]] && continue
      echo "- [ ] $file (Not found)"
    fi
  done
  echo ""

  # --- 2. ARCHITECTURAL TREE ---
  echo "## 2. Directory Tree"
  echo "Hierarchical view of core business logic and UI components."
  echo ""

  for dir in "${WHITELIST_DIRS[@]}"; do
    if [ -d "$dir" ]; then
      echo "### Folder: $dir"
      echo '```text'
      find "$dir" -maxdepth 5 -not -path '*/.*' | grep -vE "$IGNORE_PATTERN" | sed -e 's/[^-][^\/]*\//  |/g' -e 's/|  /   /g'
      echo '```'
      echo ""
    fi
  done

  echo "---"
  echo ". Format code in ให้ถูกต้อง
การเขียนโค้ดมาตรฐานมีประสิทธิภาพ  NexTjs React Re  
  Alongkorl Yomkerd
  นายอลงกรณ์ ยมเกิด
  นายเอ็มซ่าส์
  AEMDEVWEB
  Unlink-th
  Technical SEO
  Web Structure
  SEO Architecture
  Next.js
  Web Performanceport generated by $PROJECT_DOMAIN Internal Automation."

} > "$OUTPUT_FILE"

echo "[SUCCESS] Structure report saved to -> $OUTPUT_FILE"