#!/bin/bash

# ==============================================================================
# 🛠️ www.aemdevweb.com: Project Structure Reporter
# ==============================================================================
# Description: Generates a markdown report of project directory structure
#              and verifies required root-level configuration files.
# Domain: https://www.aemdevweb.com
# ==============================================================================

# ⚙️ CONFIGURATION
OUTPUT_FILE="me.aemdevweb-structure.md"
PROJECT_DOMAIN="www.me.aemdevweb.com"
PROJECT_URL="https://www.me.aemdevweb.com"

# Directories allowed for scanning (Strictly aligned with Next.js 15 App Router)
WHITELIST_DIRS=(
  "app"
  "demo"
  "actions"
  "components"
  "lib"
  "hooks"
  "types"
  "public"
  "data"
  "constants"
  "providers"
  "content"
  "styles"
  "services"
  "config"
  "viewport"
)

# Required root-level configuration files
ROOT_FILES=(
  "eslint.config.mjs"
  "mdx-components.tsx"
  "next.config.ts"
  "package.json"
  "components.json"
  "tsconfig.json"
  "postcss.config.mjs"
)

# Regex to ignore non-essential or sensitive files
IGNORE_PATTERN="node_modules|\.git|\.next|\.DS_Store|__pycache__|\.env"

# 🚀 START EXECUTION
rm -f "$OUTPUT_FILE"

echo "🔍 Scanning $PROJECT_DOMAIN project architecture..."

{
  echo "# 📁 Project Structure Report"
  echo ""
  echo "<!--"
  echo "  Domain: $PROJECT_DOMAIN"
  echo "  Canonical: $PROJECT_URL"
  echo "  Generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "  Type: Architecture / Documentation"
  echo "-->"
  echo ""
  echo "> **Project:** $PROJECT_DOMAIN  "
  echo "> **URL:** $PROJECT_URL  "
  echo "> **Generated on:** $(date '+%Y-%m-%d %H:%M:%S')"
  echo ""

  # --- ROOT CONFIGURATION FILES ---
  echo "## ⚙️ Root Configuration Files"
  echo "The following files are validated at the project root."
  echo ""

  for file in "${ROOT_FILES[@]}"; do
    if [ -f "$file" ]; then
      echo "- 📄 **$file**"
    else
      echo "- ❌ **$file** _(missing)_"
    fi
  done

  echo ""

  # --- ARCHITECTURAL OVERVIEW ---
  echo "## 🌳 Directory Tree"
  echo "The following structure represents the core business logic and UI layers."
  echo ""

  for dir in "${WHITELIST_DIRS[@]}"; do
    if [ -d "$dir" ]; then
      echo "### 📂 $dir"

      find "$dir" -maxdepth 10 -not -path '*/.*' \
        | grep -vE "$IGNORE_PATTERN" \
        | while read -r path; do

          depth=$(temp="${path//[^\/]/}"; echo "${#temp}")
          indent=$(printf '%*s' $((depth * 2)) "")
          name=$(basename "$path")

          if [ -d "$path" ]; then
            [[ "$path" != "$dir" ]] && echo "${indent}📂 **$name/**"
          else
            echo "${indent}📄 $name"
          fi
        done

      echo ""
    fi
  done

  echo "---"
  echo "_Report generated by $PROJECT_DOMAIN Internal Automation._"

} > "$OUTPUT_FILE"

echo "✅ Success: Report saved to → $OUTPUT_FILE"