#!/bin/bash

# ==============================================================================
# PROJECT: me.aemdevweb.com (Personal Authority Domain)
# DESCRIPTION: Metadata & Project Structure Reporter (Personal Knowledge Base)
# VERSION: 2.4.0 (2026-01-26)
# IDENTITY: Alongkorl Yomkerd (นายอลงกรณ์ ยมเกิด / นายเอ็มซ่ามากส์)
# ==============================================================================

# CONFIGURATION
OUTPUT_FILE="me.aemdevweb-structure.md"
PROJECT_DOMAIN="me.aemdevweb.com"
PROJECT_URL="https://me.aemdevweb.com"

# Site Identity
SITE_NAME="ME.AEMDEVWEB"
SITE_TYPE="Personal Knowledge Base / blog "

# Person
AUTHOR="Alongkorl Yomkerd"
EXPERT="นายอลงกรณ์ ยมเกิด"
ALIAS="นายเอ็มซ่ามากส์"

# Description (Narrative-first, Non-commercial)
DESCRIPTION="พื้นที่บันทึกประสบการณ์ งานที่เคยทำ และมุมมองด้านโครงสร้างเว็บและ Technical SEO ของ Alongkorl Yomkerd ผู้อยู่เบื้องหลัง Unlink-th และ AEMDEVWEB"

# Keywords (Entity-first, ลด role / service intent)
KEYWORDS=(
  "Alongkorl Yomkerd"
  "นายอลงกรณ์ ยมเกิด"
  "นายเอ็มซ่ามากส์"
  "AEMDEVWEB"
  "Unlink-th"
  "Technical SEO"
  "Web Structure"
  "SEO Architecture"
  "Next.js"
  "Web Performance"
  "Personal Writings"
  "Web Development Notes"
)

# Social Profiles (Author Authority Signals)
SOCIAL_LINKS=(
  "LinkedIn|https://www.linkedin.com/in/alongkorl-aemdevweb|#0A66C2"
  "Line Official|https://lin.ee/dDHISbG|#00B900"
  "AEMDEVWEB Page|https://www.facebook.com/aemdevweb|#1877F2"
  "Unlink-th Line|https://lin.ee/EkHkRvI|#00B900"
  "Unlink-th Official|https://www.facebook.com/profile.php?id=61586111353518|#1877F2"
)

# Directory Scope (Observed + Allowed)
WHITELIST_DIRS=(
  "app"
  "components"
  "lib"
  "public"
  "constants"
  "content"
  "config"
)

# Required root-level configuration files
ROOT_FILES=(
  "eslint.config.mjs"
  "mdx-components.tsx"
  "next.config.ts"
  "package.json"
  "components.json"
  "tsconfig.json"
  "postcss.config.mjs"
)

# Ignore patterns
IGNORE_PATTERN="node_modules|\.git|\.next|\.DS_Store|__pycache__|\.env"

# INIT
rm -f "$OUTPUT_FILE"
echo "[INFO] Generating Metadata & Structure Report for $PROJECT_DOMAIN..."

{
  # --- YAML FRONT MATTER ---
  echo "---"
  echo "title: \"$AUTHOR – Technical SEO & Web Structure Notes\""
  echo "site: \"$PROJECT_DOMAIN\""
  echo "url: \"$PROJECT_URL\""
  echo "author: \"$AUTHOR\""
  echo "expert: \"$EXPERT\""
  echo "description: \"$DESCRIPTION\""
  echo "keywords: [\"$(IFS=','; echo "${KEYWORDS[*]}")\"]"
  echo "social:"
  for link in "${SOCIAL_LINKS[@]}"; do
    IFS="|" read -r name href color <<< "$link"
    echo "  - name: \"$name\""
    echo "    href: \"$href\""
    echo "    color: \"$color\""
  done
  echo "generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "type: Personal Knowledge Base"
  echo "---"
  echo ""
  echo "# Project Metadata & Structure Report"
  echo ""
  echo "> Domain: $PROJECT_DOMAIN"
  echo "> URL: $PROJECT_URL"
  echo "> Generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "> Identity: $EXPERT / $AUTHOR"
  echo ""

  # --- 1. Root Configuration ---
  echo "## 1. Root Configuration Files"
  echo "Detected configuration and system files at project root."
  echo ""
  for file in "${ROOT_FILES[@]}"; do
    if [ -f "$file" ]; then
      echo "- [x] $file"
    else
      echo "- [ ] $file (Not found)"
    fi
  done
  echo ""

  # --- 2. Directory Tree ---
  echo "## 2. Directory Tree"
  echo "Overview of directories relevant to content, structure, and presentation."
  echo ""
  for dir in "${WHITELIST_DIRS[@]}"; do
    if [ -d "$dir" ]; then
      echo "### Folder: $dir"
      echo '```text'
      find "$dir" -maxdepth 5 -not -path '*/.*' | grep -vE "$IGNORE_PATTERN" \
        | sed -e 's/[^-][^\/]*\//  |/g' -e 's/|  /   /g'
      echo '```'
      echo ""
    else
      echo "[INFO] Directory not present: $dir"
    fi
  done

  echo "---"
  echo "Report generated by $PROJECT_DOMAIN internal tooling."
} > "$OUTPUT_FILE"

echo "[SUCCESS] Report saved -> $OUTPUT_FILE"