#!/bin/bash

# ==============================================================================
# PROJECT: me.aemdevweb.com (Authority Domain)
# DESCRIPTION: Full Context & Code Analysis Script (Production Grade)
# VERSION: 2.2.0 (2026-01-23)
# IDENTITY: Alongkorl Yomkerd (นายเอ็มซ่ามากส์)
# ==============================================================================

# CONFIGURATION
OUTPUT_FILE="aemdevweb-summary-with-code.md"
REPORT_FILE="pre-deploy-report.md"

PROJECT_DOMAIN="me.aemdevweb.com"
PROJECT_URL="https://me.aemdevweb.com"
PROJECT_NAME="AEM DevWeb Platform"
AUTHOR="Alongkorl Yomkerd"
ENVIRONMENT="production"
CONTENT_TYPE="technical-documentation"
BUILD_ID=$(git rev-parse --short HEAD 2>/dev/null || echo "local")

# Comprehensive Whitelist for Next.js 16 Enterprise Structure
WHITELIST_DIRS=(
  "app"
  "actions"
  "components"
  "lib"
  "hooks"
  "types"
  "scripts"
  "public"
  "data"
  "constants"
  "providers"
  "content"
  "styles"
  "services"
  "config"
)

# Critical files for AI / AEM / Security Context Analysis
SCAN_FILES=(
  "config/ai-context.core.md"
  "config/ai-system-role.md"
  "config/ai-context.dna.md"
  "$REPORT_FILE"
  "app/globals.css"
  "app/layout.tsx"
  "app/instrumentation.ts"
  "proxy.ts"
  "app/page.tsx"
  "components/profile/Schema.tsx"
  "mdx-components.tsx"
  "tsconfig.json"
  "next.config.ts"
  "next.config.mjs"
  "package.json"
  "types/index.ts"
  ".env"
)

# INITIALIZATION
rm -f "$OUTPUT_FILE"
echo "[INFO] Initiating Full Context Scan for $PROJECT_DOMAIN..."

{
  # FRONT MATTER METADATA (YAML Standards)
  cat <<EOF
---
title: "Project Context Summary"
description: "Full context, architecture and code analysis for AEM DevWeb Authority Platform"
author: "$AUTHOR"
site: "$PROJECT_URL"
domain: "$PROJECT_DOMAIN"
projectName: "$PROJECT_NAME"
environment: "$ENVIRONMENT"
contentType: "$CONTENT_TYPE"
buildId: "$BUILD_ID"
generatedAt: "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
status: "verified"
tags:
  - nextjs-16
  - authority-domain
  - technical-audit
  - security-context
---

# Project Context Summary (Full Scan)

> Project: $PROJECT_NAME
> Domain: $PROJECT_DOMAIN
> Identity: นายเอ็มซ่ามากส์ (Authority Entity)
> Build ID: $BUILD_ID
> Type: Full System Context | AI-Optimized | Industrial Mindset

Generated on: $(date '+%Y-%m-%d %H:%M:%S')

EOF

  # 1. PROJECT HEALTH STATUS
  echo "## 1. Project Health and Deployment Readiness"
  if [ -f "$REPORT_FILE" ]; then
    if grep -qi "READY FOR DEPLOY" "$REPORT_FILE"; then
      echo "Status: READY FOR DEPLOY (All production protocols satisfied)"
    else
      echo "Status: FIX REQUIRED (Potential impediments detected)"
    fi
    echo ""

    if grep -q "###.*Route" "$REPORT_FILE"; then
      echo "### Production Route Map"
      echo '```text'
      sed -n '/###.*Route/,/---/p' "$REPORT_FILE" | grep -vE "###|---" | sed '/^$/d'
      echo '```'
    fi
  else
    echo "Warning: $REPORT_FILE not found. Integrity metrics skipped."
  fi
  echo ""

  # 2. FILE STATISTICS
  echo "## 2. File Statistics by Extension"
  echo '```text'
  find "${WHITELIST_DIRS[@]}" -type f 2>/dev/null | sed 's/.*\.//' | sort | uniq -c | sort -nr
  echo '```'
  echo ""

  # 3. ARCHITECTURAL TREE
  echo "## 3. Directory Structure (Enterprise Tree)"
  echo '```text'
  for dir in "${WHITELIST_DIRS[@]}"; do
    if [ -d "$dir" ]; then
      echo "dir: $dir/"
      find "$dir" -maxdepth 4 -not -path '*/.*' | sed -e 's/[^-][^\/]*\//  |/g' -e 's/|  /   /g'
    fi
  done
  echo '```'
  echo ""

  # 4. SOURCE CODE CONTEXT
  echo "## 4. Critical Code Analysis and Environment Context"
  for file in "${SCAN_FILES[@]}"; do
    if [ -f "$file" ]; then
      echo "### Path: $file"

      ext="${file##*.}"
      lang="text"
      case "$ext" in
        ts|tsx) lang="typescript" ;;
        js|mjs) lang="javascript" ;;
        json) lang="json" ;;
        md) lang="markdown" ;;
        css) lang="css" ;;
      esac

      echo '```'"$lang"
      if [[ "$file" == *".env"* ]]; then
        sed 's/=\(.*\)/= "REDACTED"/' "$file"
      elif [ "$file" = "package.json" ] && command -v jq >/dev/null 2>&1; then
        jq '{name, version, scripts, dependencies, devDependencies}' package.json
      else
        cat "$file"
      fi
      echo '```'
      echo "---"
      echo ""
    fi
  done

  # SUMMARY
  echo "## Summary"
  echo "Documentation compiled successfully for $PROJECT_DOMAIN."
  echo "Focus: Authority Verification, Edge Runtime Logic, and E-E-A-T Compliance."
  echo ""
  echo "Report generated by $PROJECT_NAME Internal Automation System."

} > "$OUTPUT_FILE"

echo "[SUCCESS] Full Scan Complete!"
echo "[INFO] Documentation saved to -> $OUTPUT_FILE"
